import { Product } from '@/types';

export const sampleProducts: Product[] = [
  {
    _id: '1',
    name: 'Structured Blazer',
    slug: 'structured-blazer',
    price: 129,
    description: 'Tailored blazer in premium wool blend with minimal silhouette.',
    category: 'women',
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Ecru'],
    images: ['https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80'],
    stock: 18,
    rating: 4.6,
    reviewsCount: 52,
    createdAt: '2026-01-10',
  },
  {
    _id: '2',
    name: 'Minimal Hoodie',
    slug: 'minimal-hoodie',
    price: 79,
    description: 'Soft brushed cotton hoodie for everyday layering.',
    category: 'men',
    sizes: ['M', 'L', 'XL'],
    colors: ['Charcoal', 'Sand'],
    images: ['https://images.unsplash.com/photo-1516826957135-700dedea698c?auto=format&fit=crop&w=900&q=80'],
    stock: 30,
    rating: 4.4,
    reviewsCount: 31,
    createdAt: '2026-02-02',
  },
  {
    _id: '3',
    name: 'Kids Bomber Jacket',
    slug: 'kids-bomber-jacket',
    price: 65,
    description: 'Lightweight bomber with ribbed cuff detail.',
    category: 'kids',
    sizes: ['S', 'M', 'L'],
    colors: ['Olive', 'Navy'],
    images: ['https://images.unsplash.com/photo-1519238359922-989348752efb?auto=format&fit=crop&w=900&q=80'],
    stock: 15,
    rating: 4.7,
    reviewsCount: 20,
    createdAt: '2026-03-01',
  },
  {
    _id: '4',
    name: 'Wide Leg Trousers',
    slug: 'wide-leg-trousers',
    price: 95,
    description: 'High-rise trousers in draped suiting fabric.',
    category: 'women',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Stone'],
    images: ['https://images.unsplash.com/photo-1467043237213-65f2da53396f?auto=format&fit=crop&w=900&q=80'],
    stock: 42,
    rating: 4.5,
    reviewsCount: 70,
    createdAt: '2026-01-24',
  },
];
