import { Product } from '@/types';

export const sampleProducts: Product[] = [
  {
    _id: '1',
    name: 'Structured Blazer',
    slug: 'structured-blazer',
    price: 130000,
    description: 'Tailored blazer with signature GENERAL star branding and premium wool blend silhouette.',
    category: 'women',
    sizes: ['S', 'M', 'L'],
    colors: ['White'],
    images: ['/images/PHOTO-2026-06-14-02-36-18.jpg'],
    stock: 18,
    rating: 4.6,
    reviewsCount: 52,
    createdAt: '2026-01-10',
  },
  {
    _id: '2',
    name: 'Minimal Hoodie',
    slug: 'minimal-hoodie',
    price: 130000,
    description: 'Soft brushed cotton hoodie finished with the GENERAL wordmark and five-star print.',
    category: 'men',
    sizes: ['M', 'L', 'XL'],
    colors: ['Black'],
    images: ['/images/PHOTO-2026-06-14-02-36-19.jpg'],
    stock: 30,
    rating: 4.4,
    reviewsCount: 31,
    createdAt: '2026-02-02',
  },
  {
    _id: '3',
    name: 'Kids Bomber Jacket',
    slug: 'kids-bomber-jacket',
    price: 130000,
    description: 'Lightweight bomber jacket with ribbed cuffs and bold GENERAL star branding.',
    category: 'kids',
    sizes: ['S', 'M', 'L'],
    colors: ['Olive'],
    images: ['/images/PHOTO-2026-06-14-02-36-18 2.jpg'],
    stock: 15,
    rating: 4.7,
    reviewsCount: 20,
    createdAt: '2026-03-01',
  },
  {
    _id: '4',
    name: 'Sand Hoodie',
    slug: 'sand-hoodie',
    price: 130000,
    description: 'Sand hoodie with signature GENERAL star branding and five-star front print.',
    category: 'women',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Sand'],
    images: ['/images/PHOTO-2026-06-14-02-36-19 2.jpg'],
    stock: 42,
    rating: 4.5,
    reviewsCount: 70,
    createdAt: '2026-01-24',
  },
];
