import { Product } from '@/types';

export const sampleProducts: Product[] = [
  {
    _id: '1',
    name: 'White Hoodie',
    slug: 'white-hoodie',
    price: 130000,
    description: 'White hoodie with signature GENERAL star branding and five-star front print.',
    category: 'women',
    sizes: ['S', 'M', 'L'],
    colors: ['White'],
    images: ['/images/PHOTO-2026-06-14-02-36-18.jpg'],
    stock: 18,
    rating: 4.6,
    reviewsCount: 52,
    createdAt: '2026-01-10',
  },
  {
    _id: '2',
    name: 'Black Hoodie',
    slug: 'black-hoodie',
    price: 130000,
    description: 'Black hoodie with signature GENERAL star branding and five-star front print.',
    category: 'men',
    sizes: ['M', 'L', 'XL'],
    colors: ['Black'],
    images: ['/images/PHOTO-2026-06-14-02-36-19.jpg'],
    stock: 30,
    rating: 4.4,
    reviewsCount: 31,
    createdAt: '2026-02-02',
  },
  {
    _id: '3',
    name: 'Olive Hoodie',
    slug: 'olive-hoodie',
    price: 130000,
    description: 'Olive hoodie with signature GENERAL star branding and five-star front print.',
    category: 'kids',
    sizes: ['S', 'M', 'L'],
    colors: ['Olive'],
    images: ['/images/PHOTO-2026-06-14-02-36-18 2.jpg'],
    stock: 15,
    rating: 4.7,
    reviewsCount: 20,
    createdAt: '2026-03-01',
  },
  {
    _id: '4',
    name: 'Sand Hoodie',
    slug: 'sand-hoodie',
    price: 130000,
    description: 'Sand hoodie with signature GENERAL star branding and five-star front print.',
    category: 'women',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Sand'],
    images: ['/images/PHOTO-2026-06-14-02-36-19 2.jpg'],
    stock: 42,
    rating: 4.5,
    reviewsCount: 70,
    createdAt: '2026-01-24',
  },
];
